[package]
name = "relm4"
authors = ["Aaron Erhardt <aaron.erhardt@t-online.de>"]
edition = "2018"
version = "0.1.0-beta.2"
description = "An idiomatic GUI library inspired by Elm and based on gtk4-rs"
repository = "https://github.com/AaronErhardt/relm4"
readme = "README.md"
license = "LGPL-3.0-or-later"
documentation = "https://aaronerhardt.github.io/docs/relm4/relm4/"

keywords = ["gui", "gtk", "gtk4"]
categories = ["gui"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { version = "0.1", optional = true }
fragile = "1"
futures-core = "0.3"
gtk = { version = "0.2", package = "gtk4" }
log = "0.4.14"
once_cell = "1.8"
tokio = { version = "1.9", optional = true, features = ["rt"] }

[features]
default = []
tokio-rt = ["tokio", "async-trait"]
