[package]
name = "relm4"
authors = ["Aaron Erhardt <aaron.erhardt@t-online.de>"]
edition = "2021"
version = "0.4.1"
description = "An idiomatic GUI library inspired by Elm and based on gtk4-rs"
repository = "https://github.com/AaronErhardt/relm4"
readme = "README.md"
license = "Apache-2.0 OR MIT"
documentation = "https://aaronerhardt.github.io/docs/relm4/relm4/"

keywords = ["gui", "gtk", "gtk4"]
categories = ["gui"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
    "relm4-components",
    "relm4-macros",
]

[dependencies]
#adw = { version = "0.2", optional = true, package = "libadwaita" }
adw = { git = "https://gitlab.gnome.org/World/Rust/libadwaita-rs", optional = true, package = "libadwaita" }

async-broadcast = "0.3.4"
async-oneshot = "0.5.0"
flume = "0.10.11"
futures = "0.3.19"
gtk = { git = "https://github.com/gtk-rs/gtk4-rs", package = "gtk4" }
#gtk = { version = "0.5", package = "gtk4" }
log = "0.4.14"
once_cell = "1.8"
tokio = { version = "1.15", features = ["rt", "rt-multi-thread"] }

#relm4-macros = { version = "0.4.1", optional = true }
relm4-macros = { path = "relm4-macros", optional = true }

[dev-dependencies]
relm4-macros = { path = "relm4-macros" }
tokio = { version = "1.15", features = ["full"] }

[features]
default = []
libadwaita = ["adw"]
macros = ["relm4-macros"]
all = ["libadwaita", "macros"]
