# Always use unix newline
newline_style                   = "Unix"

# Use field init shorthand when possible
use_field_init_shorthand        = true

# NIGHTLY OPTIONS: ENABLE AS SOON AS THEY BECOME STABLE
# Reorder types and consts before methods
# reorder_impl_items              = true

# Format doc comments as well
# format_code_in_doc_comments     = true

# Change import granularity
# imports_granularity             = "Module"

# Sort group imports
# group_imports                   = "StdExternalCrate"